-- Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    exam_level VARCHAR(20) CHECK (exam_level IS NULL OR exam_level IN ('PROFESSIONAL', 'SUB_PROFESSIONAL')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    diagnostic_completed_at TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS diagnostic_completed_at TIMESTAMP;
ALTER TABLE users ADD COLUMN IF NOT EXISTS exam_level VARCHAR(20);


-- Subjects
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_professional BOOLEAN NOT NULL DEFAULT FALSE,
    is_sub_professional BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_professional BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_sub_professional BOOLEAN NOT NULL DEFAULT FALSE;

-- Repair subjects stuck invisible on both tracks (e.g. pre-fix Excel import).
UPDATE subjects
SET is_professional = TRUE, is_sub_professional = TRUE
WHERE is_professional = FALSE AND is_sub_professional = FALSE;

-- Questions
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    prompt VARCHAR(1000) NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    explanation VARCHAR(2000),
    image_url VARCHAR(500),
    batch_label VARCHAR(100),
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

-- Existing H2 file DBs created before explanation / image_url / batch_label existed
ALTER TABLE questions ADD COLUMN IF NOT EXISTS explanation VARCHAR(2000);
ALTER TABLE questions ADD COLUMN IF NOT EXISTS image_url VARCHAR(500);
ALTER TABLE questions ADD COLUMN IF NOT EXISTS batch_label VARCHAR(100);
CREATE INDEX IF NOT EXISTS idx_questions_batch_label ON questions(batch_label);

-- Exams
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    duration_minutes INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_diagnostic BOOLEAN NOT NULL DEFAULT FALSE,
    questions_per_subject INT,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_diagnostic BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS questions_per_subject INT;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_weekly BOOLEAN NOT NULL DEFAULT FALSE;

-- Exam Questions
CREATE TABLE IF NOT EXISTS exam_questions (
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (exam_id, question_id),
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Exam Attempts
CREATE TABLE IF NOT EXISTS exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    exam_id BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    score_percent DECIMAL(5,2),
    status VARCHAR(20) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'EXPIRED')),
    leave_count INT NOT NULL DEFAULT 0,
    suspect_leave_count INT NOT NULL DEFAULT 0,
    integrity_tracking BOOLEAN NOT NULL DEFAULT TRUE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
);

ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS leave_count INT NOT NULL DEFAULT 0;
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS suspect_leave_count INT NOT NULL DEFAULT 0;
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS integrity_tracking BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS attempt_kind VARCHAR(20) DEFAULT 'PRACTICE';
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS regimen_id BIGINT;
ALTER TABLE exam_attempts ADD COLUMN IF NOT EXISTS duration_minutes_override INT;

UPDATE exam_attempts SET attempt_kind = 'DIAGNOSTIC'
WHERE (attempt_kind IS NULL OR attempt_kind = 'PRACTICE') AND exam_id IN (
    SELECT id FROM exams WHERE is_diagnostic = TRUE
);
UPDATE exam_attempts SET attempt_kind = 'PRACTICE' WHERE attempt_kind IS NULL;

-- Attempt Answers
CREATE TABLE IF NOT EXISTS attempt_answers (
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option CHAR(1) CHECK (selected_option IN ('A', 'B', 'C', 'D')),
    is_correct BOOLEAN,
    PRIMARY KEY (attempt_id, question_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Attempt Questions (sampled set for diagnostic attempts)
CREATE TABLE IF NOT EXISTS attempt_questions (
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (attempt_id, question_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Diagnostic subject scores (snapshot on submit)
CREATE TABLE IF NOT EXISTS diagnostic_subject_scores (
    attempt_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    score_percent DECIMAL(5,2) NOT NULL,
    band VARCHAR(20) NOT NULL CHECK (band IN ('STRONG', 'DEVELOPING', 'WEAK')),
    PRIMARY KEY (attempt_id, subject_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

-- Examinee leave/return events (integrity)
CREATE TABLE IF NOT EXISTS attempt_behavior_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    event_type VARCHAR(10) NOT NULL CHECK (event_type IN ('LEAVE', 'RETURN')),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    question_answered BOOLEAN NOT NULL,
    remaining_question_ms INT,
    away_duration_ms INT,
    suspect BOOLEAN NOT NULL DEFAULT FALSE,
    question_difficulty VARCHAR(20),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_behavior_events_attempt ON attempt_behavior_events(attempt_id);
CREATE INDEX IF NOT EXISTS idx_exam_attempts_suspect ON exam_attempts(suspect_leave_count);

-- Access grants (funnel purchase tokens — hash stored, raw returned once)
CREATE TABLE IF NOT EXISTS access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('UNUSED', 'REDEEMED', 'REVOKED')),
    expires_at TIMESTAMP NOT NULL,
    redeemed_at TIMESTAMP,
    user_id BIGINT,
    plan_code VARCHAR(50),
    source_ref VARCHAR(100),
    exam_level VARCHAR(20) CHECK (exam_level IS NULL OR exam_level IN ('PROFESSIONAL', 'SUB_PROFESSIONAL')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

ALTER TABLE access_grants ADD COLUMN IF NOT EXISTS exam_level VARCHAR(20);

CREATE INDEX IF NOT EXISTS idx_access_grants_user_id ON access_grants(user_id);
CREATE INDEX IF NOT EXISTS idx_access_grants_status ON access_grants(status);

-- Weekly regimen (one official form per user per week)
CREATE TABLE IF NOT EXISTS weekly_regimens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    week_number INT NOT NULL,
    week_start TIMESTAMP NOT NULL,
    week_end TIMESTAMP NOT NULL,
    status VARCHAR(20) NOT NULL CHECK (status IN ('OPEN', 'COMPLETED', 'MISSED')),
    is_final_week BOOLEAN NOT NULL DEFAULT FALSE,
    official_attempt_id BIGINT,
    email_sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (user_id, week_number),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_form_questions (
    regimen_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (regimen_id, question_id),
    FOREIGN KEY (regimen_id) REFERENCES weekly_regimens(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS weekly_subject_scores (
    regimen_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    score_percent DECIMAL(5,2) NOT NULL,
    band VARCHAR(20) NOT NULL CHECK (band IN ('STRONG', 'DEVELOPING', 'WEAK')),
    PRIMARY KEY (regimen_id, subject_id),
    FOREIGN KEY (regimen_id) REFERENCES weekly_regimens(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS email_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    regimen_id BIGINT,
    to_address VARCHAR(100) NOT NULL,
    subject VARCHAR(200) NOT NULL,
    body VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (regimen_id) REFERENCES weekly_regimens(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_weekly_regimens_user ON weekly_regimens(user_id, week_number);
CREATE INDEX IF NOT EXISTS idx_email_outbox_user ON email_outbox(user_id);

-- Seed admin user is created programmatically on startup if missing (admin / admin123)

-- Seed sample subjects (visible to both exam tracks)
MERGE INTO subjects (id, name, description, is_professional, is_sub_professional) KEY(id) VALUES
(1, 'General Knowledge', 'Basic general knowledge questions for practice', TRUE, TRUE);
MERGE INTO subjects (id, name, description, is_professional, is_sub_professional) KEY(id) VALUES
(2, 'Numerical Ability', 'Arithmetic and number problems', TRUE, TRUE);

-- Seed sample questions (enough bank for weekly sampling)
MERGE INTO questions (id, subject_id, prompt, option_a, option_b, option_c, option_d, correct_option, difficulty, explanation) KEY(id) VALUES
(1, 1, 'What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 'C', 'EASY', 'Paris is the capital of France.'),
(2, 1, 'Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B', 'EASY', 'Mars appears red from iron oxide on its surface.'),
(3, 1, 'What is 15 + 27?', '40', '41', '42', '43', 'C', 'EASY', '15 + 27 = 42.'),
(4, 1, 'Who wrote Romeo and Juliet?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B', 'MEDIUM', 'Shakespeare wrote Romeo and Juliet.'),
(5, 1, 'What is the chemical symbol for water?', 'O2', 'CO2', 'H2O', 'NaCl', 'C', 'EASY', 'Water is two hydrogen atoms and one oxygen atom.'),
(6, 1, 'Which ocean is the largest?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 'D', 'EASY', 'The Pacific is the largest ocean.'),
(7, 1, 'In which continent is Egypt?', 'Asia', 'Africa', 'Europe', 'South America', 'B', 'EASY', 'Egypt is in northeastern Africa.'),
(8, 1, 'What gas do plants absorb?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Helium', 'C', 'MEDIUM', 'Plants absorb carbon dioxide for photosynthesis.'),
(9, 1, 'How many days are in a leap year?', '364', '365', '366', '367', 'C', 'EASY', 'A leap year has 366 days.'),
(10, 1, 'Which instrument measures temperature?', 'Barometer', 'Thermometer', 'Hygrometer', 'Altimeter', 'B', 'EASY', 'A thermometer measures temperature.'),
(11, 1, 'What is the largest mammal?', 'Elephant', 'Blue whale', 'Giraffe', 'Hippopotamus', 'B', 'MEDIUM', 'The blue whale is the largest mammal.'),
(12, 1, 'Which metal is liquid at room temperature?', 'Iron', 'Mercury', 'Gold', 'Copper', 'B', 'HARD', 'Mercury is liquid at standard room temperature.'),
(13, 2, 'What is 8 × 7?', '54', '56', '58', '64', 'B', 'EASY', '8 × 7 = 56.'),
(14, 2, 'What is 25% of 80?', '15', '20', '25', '30', 'B', 'EASY', '0.25 × 80 = 20.'),
(15, 2, 'What is the next number: 2, 4, 8, 16, ?', '18', '24', '32', '64', 'C', 'MEDIUM', 'Each term doubles: 16 × 2 = 32.'),
(16, 2, 'If a train travels 60 km in 45 minutes, what is its speed in km/h?', '75', '80', '90', '120', 'B', 'MEDIUM', '60 km in 0.75 h is 80 km/h.'),
(17, 2, 'What is 3² + 4²?', '7', '12', '25', '49', 'C', 'EASY', '9 + 16 = 25.'),
(18, 2, 'Simplify 2/5 + 1/5.', '1/5', '2/5', '3/5', '4/5', 'C', 'EASY', '2/5 + 1/5 = 3/5.'),
(19, 2, 'A shirt costs 400 after a 20% discount. What was the original price?', '480', '500', '520', '600', 'B', 'HARD', '400 is 80% of the original, so original = 500.'),
(20, 2, 'What is the average of 10, 20, and 30?', '15', '20', '25', '30', 'B', 'EASY', '(10 + 20 + 30) / 3 = 20.'),
(21, 2, 'How many minutes are in 2.5 hours?', '120', '130', '150', '180', 'C', 'EASY', '2.5 × 60 = 150.'),
(22, 2, 'If 5x = 45, what is x?', '7', '8', '9', '10', 'C', 'EASY', 'x = 45 / 5 = 9.');

-- Seed sample exam
MERGE INTO exams (id, subject_id, title, duration_minutes, is_active, is_diagnostic, questions_per_subject, is_weekly) KEY(id) VALUES
(1, 1, 'General Knowledge Practice Test', 10, TRUE, FALSE, NULL, FALSE);

-- Seed diagnostic exam (samples from question bank; activate after subjects/questions exist)
MERGE INTO exams (id, subject_id, title, duration_minutes, is_active, is_diagnostic, questions_per_subject, is_weekly) KEY(id) VALUES
(2, 1, 'Placement Diagnostic', 30, TRUE, TRUE, 5, FALSE);

-- Seed weekly exam template (questions sampled per user per week)
MERGE INTO exams (id, subject_id, title, duration_minutes, is_active, is_diagnostic, questions_per_subject, is_weekly) KEY(id) VALUES
(3, 1, 'Weekly Exam', 40, TRUE, FALSE, 4, TRUE);

-- Link questions to practice exam
MERGE INTO exam_questions (exam_id, question_id, sort_order) KEY(exam_id, question_id) VALUES
(1, 1, 1),
(1, 2, 2),
(1, 3, 3),
(1, 4, 4),
(1, 5, 5);
