-- Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    email VARCHAR(100) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(10) NOT NULL CHECK (role IN ('ADMIN', 'USER')),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    diagnostic_completed_at TIMESTAMP
);

ALTER TABLE users ADD COLUMN IF NOT EXISTS diagnostic_completed_at TIMESTAMP;

-- Subjects
CREATE TABLE IF NOT EXISTS subjects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    is_professional BOOLEAN NOT NULL DEFAULT FALSE,
    is_sub_professional BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_professional BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE subjects ADD COLUMN IF NOT EXISTS is_sub_professional BOOLEAN NOT NULL DEFAULT FALSE;

-- Questions
CREATE TABLE IF NOT EXISTS questions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    prompt VARCHAR(1000) NOT NULL,
    option_a VARCHAR(500) NOT NULL,
    option_b VARCHAR(500) NOT NULL,
    option_c VARCHAR(500) NOT NULL,
    option_d VARCHAR(500) NOT NULL,
    correct_option CHAR(1) NOT NULL CHECK (correct_option IN ('A', 'B', 'C', 'D')),
    difficulty VARCHAR(20) NOT NULL DEFAULT 'MEDIUM',
    explanation VARCHAR(2000),
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

-- Existing H2 file DBs created before explanation existed
ALTER TABLE questions ADD COLUMN IF NOT EXISTS explanation VARCHAR(2000);

-- Exams
CREATE TABLE IF NOT EXISTS exams (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    subject_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL,
    duration_minutes INT NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    is_diagnostic BOOLEAN NOT NULL DEFAULT FALSE,
    questions_per_subject INT,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

ALTER TABLE exams ADD COLUMN IF NOT EXISTS is_diagnostic BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE exams ADD COLUMN IF NOT EXISTS questions_per_subject INT;

-- Exam Questions
CREATE TABLE IF NOT EXISTS exam_questions (
    exam_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (exam_id, question_id),
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Exam Attempts
CREATE TABLE IF NOT EXISTS exam_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    exam_id BIGINT NOT NULL,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    score_percent DECIMAL(5,2),
    status VARCHAR(20) NOT NULL CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'EXPIRED')),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (exam_id) REFERENCES exams(id) ON DELETE CASCADE
);

-- Attempt Answers
CREATE TABLE IF NOT EXISTS attempt_answers (
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    selected_option CHAR(1) CHECK (selected_option IN ('A', 'B', 'C', 'D')),
    is_correct BOOLEAN,
    PRIMARY KEY (attempt_id, question_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Attempt Questions (sampled set for diagnostic attempts)
CREATE TABLE IF NOT EXISTS attempt_questions (
    attempt_id BIGINT NOT NULL,
    question_id BIGINT NOT NULL,
    sort_order INT NOT NULL,
    PRIMARY KEY (attempt_id, question_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (question_id) REFERENCES questions(id) ON DELETE CASCADE
);

-- Diagnostic subject scores (snapshot on submit)
CREATE TABLE IF NOT EXISTS diagnostic_subject_scores (
    attempt_id BIGINT NOT NULL,
    subject_id BIGINT NOT NULL,
    score_percent DECIMAL(5,2) NOT NULL,
    band VARCHAR(20) NOT NULL CHECK (band IN ('STRONG', 'DEVELOPING', 'WEAK')),
    PRIMARY KEY (attempt_id, subject_id),
    FOREIGN KEY (attempt_id) REFERENCES exam_attempts(id) ON DELETE CASCADE,
    FOREIGN KEY (subject_id) REFERENCES subjects(id) ON DELETE CASCADE
);

-- Access grants (funnel purchase tokens — hash stored, raw returned once)
CREATE TABLE IF NOT EXISTS access_grants (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(20) NOT NULL CHECK (status IN ('UNUSED', 'REDEEMED', 'REVOKED')),
    expires_at TIMESTAMP NOT NULL,
    redeemed_at TIMESTAMP,
    user_id BIGINT,
    plan_code VARCHAR(50),
    source_ref VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_access_grants_user_id ON access_grants(user_id);
CREATE INDEX IF NOT EXISTS idx_access_grants_status ON access_grants(status);

-- Seed admin user is created programmatically on startup if missing (admin / admin123)

-- Seed sample subject
MERGE INTO subjects (id, name, description) KEY(id) VALUES
(1, 'General Knowledge', 'Basic general knowledge questions for practice');

-- Seed sample questions
MERGE INTO questions (id, subject_id, prompt, option_a, option_b, option_c, option_d, correct_option, difficulty) KEY(id) VALUES
(1, 1, 'What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 'C', 'EASY'),
(2, 1, 'Which planet is known as the Red Planet?', 'Venus', 'Mars', 'Jupiter', 'Saturn', 'B', 'EASY'),
(3, 1, 'What is 15 + 27?', '40', '41', '42', '43', 'C', 'EASY'),
(4, 1, 'Who wrote Romeo and Juliet?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B', 'MEDIUM'),
(5, 1, 'What is the chemical symbol for water?', 'O2', 'CO2', 'H2O', 'NaCl', 'C', 'EASY');

-- Seed sample exam
MERGE INTO exams (id, subject_id, title, duration_minutes, is_active, is_diagnostic, questions_per_subject) KEY(id) VALUES
(1, 1, 'General Knowledge Practice Test', 10, TRUE, FALSE, NULL);

-- Seed diagnostic exam (samples from question bank; activate after subjects/questions exist)
MERGE INTO exams (id, subject_id, title, duration_minutes, is_active, is_diagnostic, questions_per_subject) KEY(id) VALUES
(2, 1, 'Placement Diagnostic', 30, TRUE, TRUE, 5);

-- Link questions to exam
MERGE INTO exam_questions (exam_id, question_id, sort_order) KEY(exam_id, question_id) VALUES
(1, 1, 1),
(1, 2, 2),
(1, 3, 3),
(1, 4, 4),
(1, 5, 5);
